vtex-apps/order-manager

CHANGELOG.md, README.md, react/OrderManager.tsx, react/__tests__/OrderManager.test.tsx, react/modules/TaskQueue.test.ts, react/modules/TaskQueue.ts
This implements the `unlisten` function which is returned by the `listen` method as described in the API. This also includes a couple of tests that cover this functionality, fixes some lint errors and updates `README.md` to include a section on how to use this module.
=> Implement unlisten

CHANGELOG.md, README.md, react/OrderManager.tsx
~Apparently doing `import { foo, bar } from 'vtex.some-app/SomeFile'` does not work in IO (the consuming app gets `undefined` for each imported element). This PR changes the way `order-manager` does its exports so they can be used by other apps.~
`OrderManager` was not using `export default` to expose its functions, so other apps were not being able to import them. This PR fixes this. This doesn't change the way this module is used.
=> Change the way exports are made

CHANGELOG.md, react/modules/TaskQueue.test.ts, react/modules/TaskQueue.ts
This adds an error code to the promise rejection message when a task gets cancelled due to another one with the same ID being pushed to the queue. This makes it easier to treat this promise rejection on the consumer side.
=> Add code to task cancelled message

CHANGELOG.md, react/__mocks__/vtex.checkout-resources/Queries.ts, react/__tests__/OrderForm.test.tsx, react/modules/TaskQueue.test.ts, react/modules/TaskQueue.ts
In the current implementation, when a task with some id is _**running**_ and another task with the same id is pushed to the queue, the promise of the first task is rejected and the second task starts running immediately. However, the first task doesn't get effectively cancelled, thus we end up having two tasks running simultaneously, which can be problematic.
This PR prevents this scenario by not cancelling tasks that are running.
`yarn test`
---|---
✔️ | Bug fix 
=> Don't cancel a running task

CHANGELOG.md, docs/README.md, react/OrderQueue.tsx, react/__tests__/OrderQueue.test.tsx, react/constants.ts, react/modules/TaskQueue.ts
Both `OrderItems` and `OrderShipping` want to perform actions conditioned on the status of the queue. In order to do that, they implemented a `ref` object controlled by the events emitted by the queue. This PR moves this logic to `OrderQueue` to avoid this copy-pasta.
In short, this adds a new helper hook `useQueueStatus` that receives the `listen` function returned by `useOrderQueue()` and returns a `ref` object containing the status of the queue (either `Pending` or `Fulfilled`).
`yarn test`
[This workspace](http://orderstatus--vtexgame1.myvtex.com/cart) can also be used for testing. I've linked to it a [modified `OrderItems`](https://github.com/vtex-apps/order-items/tree/chore/queue-status) that uses this new hook.
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking …
=> Implement useQueueStatus

CHANGELOG.md, react/OrderForm.tsx, react/utils/dummyOrderForm.ts
This PR adds a dummy order-form object to `LoadingState` in order to display `product-list`'s preview skeleton.
- Go to [Workspace](https://productskeleton--checkoutio.myvtex.com/cart)
- Verify that it's displaying a skeleton.
---|---
_ | Bug fix 
✔️ | New feature 
=> Add dummyOrderForm object in order to display product-list skeleton

CHANGELOG.md, docs/README.md, react/OrderQueue.tsx, react/modules/TaskQueue.test.ts, react/modules/TaskQueue.ts
This PR does two things:
- Exposes the `.cancel()` method of the promise returned by `SequentialTaskQueue`;
- Adds a function `isWaiting(id: string) => boolean` which returns whether a task with the given `id` is in the queue and hasn't been run yet.
Both of those changes will be used to implement the optimization of merging `OrderItems` tasks.
`yarn test`
Alternatively, you can play around with [this workspace](https://merge--checkoutio.myvtex.com/cart/add?sku=291&sku=256&sku=287&sku=308&sku=288&sku=306&sku=330&sku=36&sku=269&sku=321)
---|---
_ | Bug fix 
✔️ | New feature 
=> Implement isWaiting function

CHANGELOG.md, react/OrderForm.tsx, react/package.json, react/yarn.lock
After the `orderForm` query was completed, a new component tree would be mounted.
That would be particularly undesirable if OrderFormContext were to be used inside of `StoreWrapper`, since the whole store would be mounted again.  
[Workspace](https://minicart--storecomponents.myvtex.com/)
---|---
✔️ | Bug fix 
_ | Technical improvements 
This should enable `OrderFormContext` to be used by `store` 🎉
=> Update rendering logic on OrderFormProvider to prevent mounting a new tree 

CHANGELOG.md, react/OrderForm.tsx
The `loading` state would not be updated on OrderFormContext and prevent `orderForm` query was being executed during SSR.
[Workspace](https://minicart--storecomponents.myvtex.com/)
---|---
✔️ | Bug fix 
=> Update loading state on OrderFormProvider and prevent SSR query

CHANGELOG.md, react/modules/SequentialTaskQueue.ts, react/modules/TaskQueue.ts, react/package.json, react/yarn.lock
The code from the imported module [`sequential-task-queue`](https://github.com/BalassaMarton/sequential-task-queue/blob/master/dist/lib/sequential-task-queue.js) was not compatible with all browsers, and was causing the store to break in IE11.
This PR moves the code to within the app so it can be properly transpiled.
Visit [this workspace](https://ieonze--storecomponents.myvtex.com/). It should load fine.
---|---
✔️ | Bug fix 
=> Copy sequential-task-queue to a module in this app

.github/workflows/testreact.yml, CHANGELOG.md, react/__tests__/OrderForm.test.tsx, react/package.json, react/utils/dummyOrderForm.ts, react/yarn.lock
Once `@vtex/test-tools` was updated to major 2 the tests started to show ugly red warnings like the ones below:
```
Warning: An update to OrderFormProvider inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
in OrderFormProvider
in ApolloProvider (created by MockedProvider)
in MockedProvider
in IntlProvider
```
This PR makes these warnings go away
`yarn test` should result in just this:
```
> yarn test
yarn run v1.19.2
warning package.json: No license field
$ vtex-test-tools test
PASS …
```
=> Remove warnings from tests

CHANGELOG.md, docs/README.md, react/OrderForm.tsx, react/package.json, react/typings/splunk-events.d.ts, react/utils/dummyOrderForm.ts, react/utils/logger.ts, react/yarn.lock
When the order form query fails, the Cart was wrongly showing the dummy order form data. This PR makes `order-manager` return an empty order form instead and log the error both to console and to Splunk. Also, this PR adds an `error` property to `OrderFormContext` so consuming components can treat this case.
Go to [this workspace](https://error--checkoutio.myvtex.com/cart). Open console and verify an error was logged. Go to [Splunk](https://splunk7.vtex.com/en-US/app/vtex_checkout_ui/search?q=search%20index%3Dcheckout_ui%20account%3Dcheckoutio&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-5m%40m&latest=now) and verify the error was logged.
---|---
✔️ | Bug fix 
=> Log error when orderForm query fails

CHANGELOG.md, react/OrderForm.tsx
When the product list is loading, it displays for a very brief moment data from a dummy order form, which is used solely as base for the loading skeleton.
The issue is a kind of a race condition on the `loading` variable set by `order-manager`. Before the changes of this PR, the `loading` variable of the context provided by `order-manager` comes directly from the `loading` value returned by the GraphQL query. This variable was used both to determine whether to display the skeleton and as a trigger to set the order form with the values returned by the query. What happened is that we were removing the skeleton before the order form was updated.
This PR fixes this problem by setting the context's `loading` property after the order form is set with the content returned by the query.
Load …
=> Fix order form loading

CHANGELOG.md, react/OrderForm.tsx
This is a temporary fix to the inconsistencies observed when navigating between departments and when going to the new cart from the store page.
We currently use the `navigate` function provided by `render-runtime` to navigate between departments. We want to use the same function to navigate from the store to the new cart, because it provides a faster and smoother transition than a simple page redirect.
However, when using this function, GraphQL data is fetched from the local cache. Due to several complications, the data for the `OrderForm` query is not properly stored in the cache, resulting in inconsistencies between server and local data.
Trying to fix the cache issue has proven itself to be more complex than I initially thought, so for now this PR removes the cache for this query to …
=> Do not use cache for orderform query

CHANGELOG.md, react/OrderForm.tsx
This adds back the cache to the OrderForm query. It was removed in https://github.com/vtex-apps/order-manager/pull/22 because it was causing inconsistencies in the UI. In order to resolve this issue, this PR also changes the behavior of the `setOrderForm` function of the `OrderFormContext`. It now updates the Apollo cache whenever the function is called. This ensures the UI remains consistent when navigating in the store.
In [this workspace](https://cache--checkoutio.myvtex.com/), add some items to the cart, click the Minicart then click Go To Checkout. Since data is fetched from cache, you should see the items you just added as soon as the page is loaded. In other words, the loading skeleton should not appear.
Now, click "Departamento 1". The Minicart icon should immediately display the …
=> Add cache to OrderForm query in Apollo

CHANGELOG.md, react/__mocks__/mockOrderForm.ts, react/typings/globals.d.ts, react/utils/dummyOrderForm.ts
Make it possible to pass the orderForm id to pixels.
[Workspace](https://breno--storecomponents.myvtex.com/)
---|---
_ | Bug fix 
✔️| New feature 
_ | Technical improvements 
Depends on:
1. https://github.com/vtex-apps/checkout-resources/pull/21
2. https://github.com/vtex/checkout-graphql/pull/44
=> Add id to OrderForm

CHANGELOG.md, react/OrderForm.tsx, react/__mocks__/vtex.checkout-resources/QueryOrderForm.ts, react/__tests__/OrderForm.test.tsx, react/typings/vtex.checkout-resources.d.ts
We are avoiding importing huge `default export`s with multiple GraphQL queries/mutations because that hinders performance. This PR changes `order-manager` to use the separate `default export`s from `checkout-resources`, which exports just a single query/mutation.
`yarn test` and [this workspace](https://split--checkoutio.myvtex.com)
---|---
_ | Bug fix 
✔️ | Technical improvements
=> Use new entrypoint for orderform query

CHANGELOG.md, package.json, react/.eslintrc, react/OrderForm.tsx, react/OrderQueue.tsx, react/__mocks__/mockOrderForm.ts, react/__mocks__/vtex.checkout-resources/QueryOrderForm.ts, react/__mocks__/vtex.render-runtime.ts, react/__tests__/OrderForm.test.tsx, react/modules/TaskQueue.ts, react/package.json, react/yarn.lock, yarn.lock
This is the foundation for some offline features that existed in the previous version of the Minicart. We will now store the order form state in `localStorage` with the latest value from the API, and will always serve this value through the context.
The `TaskQueue#enqueue` method was also updated to only execute when the user has an active internet connection by checking `navigator.onLine` (this isn't reliable). When we receive an error when the request is in-flight, we will check if the user is still online, and if they aren't we will wait for a connection before trying again.
Although the usage of `navigator.onLine` isn't really [reliable](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine), it is the only indicator the platform gives us. We could improve this logic …
=> Add offline support in order form

CHANGELOG.md, react/package.json, react/utils/logger.ts, react/yarn.lock
When I added the logger to order-manager I copy-pasted the code from somewhere else and the `axios` dependency came with it, but it is not necessary to run. We're removing it because it hinders performance.
I'm also removing `ramda` from `package.json` since we're not using it anywhere.
Go to [this workspace](https://logger--checkoutio.myvtex.com/), then check [Splunk](https://splunk7.vtex.com/en-US/app/vtex_checkout_ui/search?q=search%20index%3Dcheckout_ui%20account%3Dcheckoutio&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-5m&latest=&sid=1582898427.557910_7978E49D-2DA3-4390-8725-263B458E7F58).
---|---
_ | Bug fix 
✔️ | Technical improvements
=> Remove axios dependency

.github/CODEOWNERS, CHANGELOG.md, react/OrderForm.tsx, react/__mocks__/mockOrderForm.ts, react/__mocks__/vtex.checkout-resources/QueryOrderForm.ts, react/__tests__/OrderForm.test.tsx, react/constants.ts, react/package.json, react/utils/heuristics.ts, react/yarn.lock
When you didn't login in the store, and proceeded to checkout, the orderForm could be in a state where the user couldn't edit its data (e.g.: data was autofilled by smartcheckout). So, if the user wanted to edit their data, they should login in the store, but this didn't trigger any change to the local orderForm, making the user see the masked data even though they are authenticated.
This PR adds a new function `shouldUpdateOrderForm` that should contain all heuristics so we know whether or not to replace the local orderForm with the remote one. We can start with this case where you are not logged in and the data was autofilled, and you login after it. One scenario I know is to update the orderForm when the remote and local ids differ, but we found some inconsistencies (see more in #33) …
=> Fix local order form update when authenticated

CHANGELOG.md, react/OrderForm.tsx, react/OrderQueue.tsx, react/__tests__/OrderForm.test.tsx
This PR fixes an issue where the orderForm would be loaded almost exclusively from the `localStorage`, which caused some bugs where if you edited the items in the legacy Cart and went back to the store it wouldn't be updated to reflect the changes you did. It also had a few issues by displaying an old orderForm which was in an invalid state (e.g. when you finished a purchase, the minicart would show all the items you just purchased instead of a blank cart).
There is 3 workspaces you should checkout to assure this won't break existing stores: [storecomponents](https://lucas--storecomponents.myvtex.com/blouse-with-knot/p?skuId=310124165) which uses the legacy cart, [GoCommerce QAStore](https://lucas--qastore.mygocommerce.com/produtocypress/p) and …
=> CHUI-33: Update local orderForm based on the remote value if possible

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, react/utils/heuristics.ts
This PR fixes an issue where if you changed the authentication state in the orderForm, we would end up using the remote value returned by Apollo's `useQuery` (which after identifying, is stale). This happened because of a fix that replaced the local orderForm with the remote if the `canEditData` property changed, and in the time this was implemented we had another approach to managing both the remote and local state of the orderForm, which relied more in the local state than in the remote one.
But now we have changed how we deal with it to always fetch the remote orderForm if it is possible and wait for the query to resolve, instead of "fallbacking" to the local value, and this guarantees that we will always see the most up to date value of the orderForm, regardless of these heuristics. …
=> Fix stale orderForm when auth state changed

CHANGELOG.md, react/OrderForm.tsx
This PR makes the orderForm query skip Apollo's cache, in order to avoid an issue when the cache hints for the orderForm query aren't available, which resulted in the orderForm query result (passed through apollo's cache) to be empty (an object with only the `__typename`).
You can see more information about this bug in the [Jira issue](https://vtex-dev.atlassian.net/browse/CHK-486).
[Workspace](https://fix486--checkoutio.myvtex.com)
To assess this is working, add one product to your cart in the workspace above and reload the page. After the page has been loaded, the minicart should display the item you added.
Here is some of the "evidence" as to why I think this is related to Apollo's cache:
The first screenshot is on a breakpoint inside Apollo's …
=> CHK-486: Add no-cache fetch policy to orderForm query
